site_name: openpilot docs
docs_dir: docs
repo_url: https://github.com/commaai/openpilot/

theme:
  name: terminal
  features:
    - navigation.side.toc.hide
    - navigation.side.indexes # Allows for the section header to have a document

nav:
  - Getting Started:
    - Index: index.md # Also acts as the first page users will see
    - What is openpilot?: getting-started/what-is-openpilot.md
    - Directory Overview: getting-started/directory-overview.md
    - Building openpilot: getting-started/building-openpilot.md
    - Need more help?: getting-started/need-more-help.md
  - How-to:
    - Index: how-to/index.md
    - Turn the speed blue: how-to/turning-the-speed-blue.md
  - Submodules:
    - Index: submodules/index.md
    - cereal : submodules/cereal.md
    - opendbc : submodules/opendbc.md
    - panda : submodules/panda.md
    - rednose : submodules/rednose.md
  - Car Porting:
    - Index: car-porting/index.md
    - What is a car port?: car-porting/what-is-a-car-port.md
    - Porting a car brand: car-porting/brand-port.md
    - Porting a car model: car-porting/model-port.md
  - Tools:
    - Index: tools/index.md
    - Cabana : tools/cabana.md
    - PlotJuggler : tools/plotjuggler.md
    - SSH : tools/ssh.md
  - Contributing :
    - Index: contributing/index.md
    - How to ask questions: contributing/esv-redirect.md
    - Guidelines: contributing/contributing-guidelines.md
  - Reference:
    - Index: reference/index.md
    - Supported cars : reference/supported-cars.md
    - About comma : reference/about-comma.md
    - Limitations : reference/LIMITATIONS.md
    - Safety : reference/SAFETY.md
